name:                wai-session-redis
version:             0.1.0.4
github:              "t4ccer/wai-session-redis"
license:             BSD3
author:              "t4ccer"
maintainer:          "t4ccer@gmail.com"
copyright:           "(c) 2021 t4ccer"
category: Web

extra-source-files:
- README.md

synopsis: Simple Redis backed wai-session backend. 
description: Simple Redis backed wai-session backend. This module allows you to store session data of wai-sessions in a Redis database.

dependencies:
- base >= 4.10.0 && < 5
- bytestring >= 0.10 && < 0.11
- data-default >= 0.7 && < 0.8
- wai >= 3.2 && < 3.3
- wai-session >= 0.3.3 && < 0.4
- hedis >= 0.14 && < 0.16
- cereal >= 0.5.8 && < 0.6
- vault >= 0.3.1 && < 0.4

library:
  source-dirs: src

executables:
  wai-session-redis-example-exe:
    main:                Main.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wai-session-redis
    - warp < 3.4
    - http-types < 0.13

tests:
  wai-session-redis-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wai-session-redis
    - hspec < 2.10
