name:                wai-session-redis
version:             0.1.0.0
github:              "t4ccer/wai-session-redis"
license:             BSD3
author:              "t4ccer"
maintainer:          "t4ccre@gmail.com"
copyright:           "t4ccer"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/t4ccer/wai-session-redis#readme>

dependencies:
- base >= 4.10.0 && < 5
- wai
- wai-session
- hedis
- bytestring
- data-default
- cereal
- vault
- hspec
- warp
- http-types

library:
  source-dirs: src

executables:
  wai-session-redis-example-exe:
    main:                Main.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wai-session-redis

tests:
  wai-session-redis-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wai-session-redis
