name:                wai-session-redis
version:             0.1.0.0
github:              "t4ccer/wai-session-redis"
license:             BSD3
author:              "t4ccer"
maintainer:          "t4ccre@gmail.com"
copyright:           "t4ccer"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/t4ccer/wai-session-redis#readme>

dependencies:
- base >= 4.10.0 && < 5
- warp
- wai
- http-types
- cookie
- hedis
- uuid
- bytestring

library:
  source-dirs: src

executables:
  wai-redis-session-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wno-unused-do-bind
    - -Wpartial-fields
    - -Wincomplete-uni-patterns
    dependencies:
    - wai-session-redis

